package com.st.ggviario.client.references;

public interface RMap
{
	/**
	 * A porta de cuminicacao é gege {g = 7 | e = 5}
	 */
	int SOCKET_PORT = 7575;

	//IDENTIFICADORES
	String IDENTIFIER_SELL_PRINCIPAL = "IDENTIFIER_SELL_PRINCIPAL";
	String IDENTIFIER_SELL_PAYMENT = "IDENTIFIER_SELL_PAYMENT";
	String IDENTIFIER_SELL_SUPPORT = "IDENTIFIER_SELL_SUPPORT";
	String IDENTIFIER_SELL_PAY_CREDIT = "IDENTIFIER_SELL_PAY_CREDIT";
	String IDENTIFIER_SELL_CLIENT_ITEM = "IDENTIFIER_SELL_CLIENT_ITEM";
	String IDENTIFIER_SELL_CLIENT_SUPPORT = "IDENTIFIER_SELL_CLIENT_SUPPORT";
	String IDENTIFIER_SELL_CLIENT_LIST = "IDENTIFIER_SELL_CLIENT_LIST";
	String IDENTIFIER_SELL_CLIENT_REGISTER = "IDENTIFIER_SELL_CLIENT_REGISTER";
	String IDENTIFIER_SELL_HOME = "IDENTIFIER_SELL_HOME";
	String IDENTIFIER_GGVIARIO = "IDENTIFIER_GGVIARIO";
	String IDENTIFIER_MAIN_HOME = "IDENTIFIER_MAIN_HOME";

	//QUERY FROM SERVER TO CLIENTS
	String QUERY_DATA_CREATOR = "QUERY_DATA_CREATOR";
	String QUERY_LIST_PRODUCTS = "QUERY_LIST_PRODUCTS";
	String QUERY_CLIENT_SELECTED = "QUERY_CLIENT_SELECTED";
	String QUERY_GET_SOCKET_SERVICE = "QUERY_GET_SOCKET_SERVICE";



	//SUMARYES
	String SUMMARY_NAVE_MY = "SUMMARY_NAVE_MY";
	String SUMMARY_NEW_REGISTER_SUCCESS = "SUMMARY_NEW_REGISTER_SUCCESS";
	String SUMMARY_NAVE_PAGER = "SUMMARY_NAVE_PAGER";
	String SUMMARY_OPEN_DRAWER = "SUMMARY_OPEN_DRAWER";
	String SUMMARY_PRODUCT_CHAGE = "SUMMARY_PRODUCT_CHAGE";
	String SUMMARY_CLIENT_CHANGED = "SUMMARY_CLIENT_CHANGED";
	String SUMMARY_CLIENT_CLICKED = "SUMMARY_CLIENT_CLICKED";
	String SUMMARY_REGISTER_TREATER_LISTNER = "SUMMARY_REGISTER_TREATER_LISTNER";;
	String ITEM_SELL = "ITEM_SELL";
	String CAR_ACTION = "CAR_ACTION";
	String HAS_IN_CAR = "HAS_IN_CAR";
	String ITEM_SELL_QUANTITY = "ITEM_SELL_QUANTITY";
	String ITEM_SELL_MEASURE = "ITEM_SELL_MEASURE";
}
